// ====================================
// FILE: src/module/wfh/wfh.model.js
// COMPLETE WFH MODEL (UPDATED - DATE RANGE)
// ====================================

import mongoose from "mongoose";

const wfhSchema = new mongoose.Schema(
  {
    // ✅ EMPLOYEE REFERENCE (MongoDB ID)
    employee_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Employee",
      required: true,
      index: true,
    },

    // ✅ EMPLOYEE NAME (Stored as backup for quick access)
    employee_name: {
      type: String,
      required: true,
      trim: true,
    },

    // ✅ START DATE (From Date)
    start_date: {
      type: Date,
      required: true,
      index: true,
    },

    // ✅ END DATE (To Date)
    end_date: {
      type: Date,
      required: true,
    },

    // ✅ NUMBER OF DAYS
    number_of_days: {
      type: Number,
      required: true,
    },

    // ✅ REASON FOR WFH
    reason: {
      type: String,
      trim: true,
      default: "",
    },

    // ✅ WFH TYPE (FULL_DAY or HALF_DAY)
    wfh_type: {
      type: String,
      enum: ["FULL_DAY", "HALF_DAY"],
      default: "FULL_DAY",
    },

    // ✅ STATUS (PENDING, APPROVED, REJECTED)
    status: {
      type: String,
      enum: ["PENDING", "APPROVED", "REJECTED"],
      default: "PENDING",
      index: true,
    },

    // ✅ APPLIED BY (Who applied - HR or Employee)
    applied_by: {
      type: String, // "HR" or employee name
      required: true,
    },

    // ✅ APPROVED BY (HR/Manager who approves)
    approved_by: {
      type: String,
      trim: true,
      default: null,
    },

    // ✅ APPROVED DATE
    approved_date: {
      type: Date,
      default: null,
    },

    // ✅ REJECTION REASON
    rejection_reason: {
      type: String,
      trim: true,
      default: "",
    },
  },
  {
    timestamps: true, // Adds createdAt and updatedAt
  }
);

// ✅ CREATE INDEXES FOR BETTER PERFORMANCE
wfhSchema.index({ employee_id: 1 });
wfhSchema.index({ status: 1 });
wfhSchema.index({ start_date: 1 });
wfhSchema.index({ end_date: 1 });
wfhSchema.index({ createdAt: -1 });
wfhSchema.index({ employee_id: 1, start_date: 1 });

const WFH = mongoose.model("WFH", wfhSchema);

export default WFH;

// ====================================
// SAMPLE WFH DOCUMENTS
// ====================================

/*
{
  "_id": ObjectId("650a1b2c3d4e5f6g7h8i9j0k"),
  "employee_id": ObjectId("650a1b2c3d4e5f6g7h8i9j0a"),
  "employee_name": "John Doe",
  "start_date": ISODate("2024-01-15T00:00:00.000Z"),
  "end_date": ISODate("2024-01-17T00:00:00.000Z"),
  "number_of_days": 3,
  "reason": "Working on project",
  "wfh_type": "FULL_DAY",
  "status": "PENDING",
  "applied_by": "HR",
  "approved_by": null,
  "approved_date": null,
  "rejection_reason": "",
  "createdAt": ISODate("2024-01-15T10:30:00.000Z"),
  "updatedAt": ISODate("2024-01-15T10:30:00.000Z"),
  "__v": 0
}

{
  "_id": ObjectId("650a1b2c3d4e5f6g7h8i9j0l"),
  "employee_id": ObjectId("650a1b2c3d4e5f6g7h8i9j0b"),
  "employee_name": "Sarah Smith",
  "start_date": ISODate("2024-01-20T00:00:00.000Z"),
  "end_date": ISODate("2024-01-20T00:00:00.000Z"),
  "number_of_days": 1,
  "reason": "Personal work",
  "wfh_type": "HALF_DAY",
  "status": "APPROVED",
  "applied_by": "Employee",
  "approved_by": "ADMIN",
  "approved_date": ISODate("2024-01-20T11:00:00.000Z"),
  "rejection_reason": "",
  "createdAt": ISODate("2024-01-20T09:00:00.000Z"),
  "updatedAt": ISODate("2024-01-20T11:00:00.000Z"),
  "__v": 0
}
*/

// ====================================
// FIELD DESCRIPTIONS
// ====================================

/*
employee_id:
  - Type: ObjectId (Reference to Employee)
  - Required: Yes
  - Used to link to Employee document
  - Automatically populated by MongoDB ref

employee_name:
  - Type: String
  - Required: Yes
  - Name of employee (stored for quick access)

start_date:
  - Type: Date
  - Required: Yes
  - WFH starts on this date

end_date:
  - Type: Date
  - Required: Yes
  - WFH ends on this date

number_of_days:
  - Type: Number
  - Required: Yes
  - Total days (calculated: end_date - start_date + 1)

reason:
  - Type: String
  - Required: No
  - Reason for WFH

wfh_type:
  - Type: String (Enum)
  - Options: FULL_DAY, HALF_DAY
  - Default: FULL_DAY

status:
  - Type: String (Enum)
  - Options: PENDING, APPROVED, REJECTED
  - Default: PENDING

applied_by:
  - Type: String
  - Who applied: "HR" or employee name
  - Required: Yes

approved_by:
  - Type: String
  - Who approved: HR/Manager name
  - Default: null

approved_date:
  - Type: Date
  - When approval happened
  - Default: null

rejection_reason:
  - Type: String
  - Reason if rejected
  - Default: ""

createdAt/updatedAt:
  - Auto-generated by mongoose
  - When record was created/updated
*/
