// ====================================
// FILE: src/module/department/department.model.js
// DEPARTMENT MODEL - FIXED SCHEMA
// ====================================

import mongoose from "mongoose";

const departmentSchema = new mongoose.Schema(
  {
    // ✅ DEPARTMENT ID (Auto-generated: DEPT001, DEPT002, etc.)
    // Generated by IdcodeServices and stored in idcodes collection
    department_id: {
      type: String,
      unique: true,
      required: true,
      index: true,
    },

    // ✅ DEPARTMENT NAME (Required, Unique)
    department_name: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      index: true,
    },

    // ✅ STATUS (Active/Inactive)
    status: {
      type: String,
      enum: ["Active", "Inactive"],
      default: "Active",
      index: true,
    },
  },
  {
    timestamps: true,
  }
);

// ✅ CREATE MODEL
const Department = mongoose.model("Department", departmentSchema);

export default Department;

// ============================================
// SAMPLE DOCUMENT IN MONGODB:
// ============================================
/*
{
  "_id": ObjectId("507f1f77bcf86cd799439011"),
  "department_id": "DEPT001",
  "department_name": "Central Operation",
  "status": "Active",
  "createdAt": ISODate("2026-03-15T10:00:00.000Z"),
  "updatedAt": ISODate("2026-03-15T10:00:00.000Z"),
  "__v": 0
}

{
  "_id": ObjectId("507f1f77bcf86cd799439012"),
  "department_id": "DEPT002",
  "department_name": "Development",
  "status": "Active",
  "createdAt": ISODate("2026-03-15T10:01:00.000Z"),
  "updatedAt": ISODate("2026-03-15T10:01:00.000Z"),
  "__v": 0
}
*/

// ============================================
// ID CODE GENERATION IN IDCODES COLLECTION:
// ============================================
/*
When first department is created:

idcodes collection:
{
  "_id": ObjectId(...),
  "idname": "Department",
  "idcode": "DEPT",
  "codes": 1
}

When second department is created:
{
  "_id": ObjectId(...),
  "idname": "Department",
  "idcode": "DEPT",
  "codes": 2
}

Each call to generateCode("Department") increments codes and returns:
1st call: "DEPT001"
2nd call: "DEPT002"
3rd call: "DEPT003"
etc.
*/
